version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/jvm/gradle"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/jvm/maven"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node/npm"
    schedule:
      interval: "weekly"
  - package-ecosystem: "go"
    directory: "/go"
    schedule:
      interval: "weekly"
  - package-ecosystem: "python"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
