version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/jvm/gradle"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/jvm/maven"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/npm"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "go"
    directory: "/go"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
