name: 'Hello World'
description: 'Greet someone'
inputs:
  ecosystem:
    description: 'ecosystem'
    required: true
  image:
    description: 'image'
    required: true
  maindir:
    description: 'maindir go'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.1'
#    - name: Install Cosign
#      uses: sigstore/cosign-installer@main
#      with:
#        cosign-release: 'main'

    - run: curl https://github.com/sigstore/cosign/releases/download/v2.0.0/cosign-linux-amd64 -o /usr/local/bin/cosign
    - name: CycloneDX GoMod Generate SBOM
      if: ${{ inputs.ecosystem == 'go' }}
      uses: CycloneDX/gh-gomod-generate-sbom@v1.1.0
      with:
        args: app -output ./sbom.json -main ${{ inputs.maindir }} -json=true