name: Go Salsa Action Example
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/gotestapp:1h

jobs:
  build-go:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          context: ./golang
      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          ecosystem: 'go'
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          workdir: 'golang'
          key: cosign.key