name: Gradle Salsa Action Example
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/gradletestapp:1h

jobs:
  build-gradle:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          context: ./jvm

      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'

     # - run: |
     #     cd jvm/gradle
     #     ./gradlew cyclonedxBom

      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          ecosystem: 'gradle'
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          #byosbom: gradle/build/reports/bom.json
          key: cosign.key
          workdir: 'jvm/gradle'
