name: Gradle Salsa Action
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/gradletestapp:1h
  CONTEXT: ci/jvm
  KEY: ci/cosign.key

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          context: ./${{ env.CONTEXT }}

      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'

      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          context: ${{ env.CONTEXT }}/gradle
          key: ${{ env.KEY }}