name: No Ecosystem with ephemeral keyless Github Token Salsa Action
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/noecosystemtestapp:1h
  CONTEXT: ci/no-ecosystem

jobs:
  build-no-ecosystem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          context: ./${{ env.CONTEXT }}

      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          context: ${{ env.CONTEXT }}