name: Npm Salsa Action
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/npmtestapp:1h
  CONTEXT: ci/node
  KEY: ci/cosign.key

jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          context: ./${{ env.CONTEXT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          context: ${{ env.CONTEXT }}/npm
          key: ${{ env.KEY }}