name: Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push image
        run: |
          docker build golang/ -t ttl.sh/salsa/gotestapp:1h && docker push ttl.sh/salsa/gotestapp:1h
      - name: Generate, sign and upload SBOM
        uses: ./
        #working-directory: golang
        with:
          ecosystem: 'go'
          image: ttl.sh/salsa/gotestapp:1h
          maindir: '.'
          workdir: 'golang'
          key: cosign.key
